### ISSUE TITLE
api:sacred_treasure/*/from_rarityがgive以外動作しない

### ISSUE THREAD

**Issue by ChenCMD** [ProjectTSB/TheSkyBlessing#1359]
`type:"give"`に上書きされてる

**Comment by haiiro2gou** [comment]
`type:"give"`をつける処理を`api:sacred_treasure/give/from_id`から削除するのが丸そうに思える
#1286 以前のデフォルト処理としてのgiveの条件を`asset:context Type`の中身が存在しないに変更する形

**Comment by ChenCMD** [comment]
> `type:"give"`をつける処理を`api:sacred_treasure/give/from_id`から削除するのが丸そうに思える
> #1286 以前のデフォルト処理としてのgiveの条件を`asset:context Type`の中身が存在しないに変更する形

あまり綺麗じゃないので別途明示的にtypeを引き継ぐやつを作るほうが綺麗かな
