### ISSUE TITLE
攻撃時にMPが回復するようにする

### ISSUE THREAD

**Issue by Lapis-LJA** [ProjectTSB/TheSkyBlessing#1513]
信仰によって近接攻撃時とか遠距離攻撃とかあったよね

**Comment by ChenCMD** [comment]
[仕様|信仰](https://discord.com/channels/742465492861845564/747111698443534376/1044173250680328232)
[仕様|分類](https://discord.com/channels/742465492861845564/747111698443534376/1074918638110380083)
