### ISSUE TITLE
シャード加工機にボートをぶつけると額縁が無限入手できる

### ISSUE THREAD

**Issue by quikku** [ProjectTSB/TheSkyBlessing#617]
対策としては埋まってたらFixed:1b、埋まってなかったらFixed:0bする（藪考案）

**Comment by yavu** [comment]
Fixed:1bだとブロックに埋まっていてもはがれないのでブロックの破壊処理が不要になる

**Comment by haiiro2gou** [comment]
https://github.com/ProjectTSB/TheSkyBlessing/blob/master/TheSkyBlessing/data/world_manager/functions/gimmick/shard_processor/.mcfunction#L12-L16
